CREATE TABLE IF NOT EXISTS schema_meta (
    meta_key TEXT PRIMARY KEY,
    meta_value TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS "groups" (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    weight INT NOT NULL DEFAULT 0,
    is_default BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    first_join TIMESTAMP,
    last_seen TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS user_groups (
    user_id TEXT NOT NULL,
    group_id INT NOT NULL,
    expires_at TIMESTAMP NULL,
    PRIMARY KEY (user_id, group_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES "groups"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_inheritance (
    group_id INT NOT NULL,
    parent_id INT NOT NULL,
    PRIMARY KEY (group_id, parent_id),
    CHECK (group_id != parent_id),
    FOREIGN KEY (group_id) REFERENCES "groups"(id) ON DELETE CASCADE,
    FOREIGN KEY (parent_id) REFERENCES "groups"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id INT NOT NULL,
    permission TEXT NOT NULL,
    allow BOOLEAN NOT NULL DEFAULT TRUE,
    context_key TEXT NULL,
    expires_at TIMESTAMP NULL,
    FOREIGN KEY (group_id) REFERENCES "groups"(id) ON DELETE CASCADE,
    UNIQUE(group_id, permission, context_key)
);

CREATE TABLE IF NOT EXISTS user_permissions (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    permission TEXT NOT NULL,
    allow BOOLEAN NOT NULL DEFAULT TRUE,
    context_key TEXT NULL,
    expires_at TIMESTAMP NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, permission, context_key)
);

CREATE TABLE IF NOT EXISTS ladders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ladder_groups (
    ladder_id INT NOT NULL,
    group_id INT NOT NULL,
    position INT NOT NULL,
    PRIMARY KEY (ladder_id, group_id),
    UNIQUE (ladder_id, position),
    FOREIGN KEY (ladder_id) REFERENCES ladders(id) ON DELETE CASCADE,
    FOREIGN KEY (group_id) REFERENCES "groups"(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS user_options (
    user_id TEXT PRIMARY KEY,
    prefix TEXT,
    suffix TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS group_options (
    group_id INT PRIMARY KEY,
    prefix TEXT,
    suffix TEXT,
    FOREIGN KEY (group_id) REFERENCES "groups"(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_users_name ON users(name);
CREATE INDEX IF NOT EXISTS idx_user_groups ON user_groups(user_id);
CREATE INDEX IF NOT EXISTS idx_group_inheritance ON group_inheritance(group_id);
CREATE INDEX IF NOT EXISTS idx_user_permissions_lookup ON user_permissions(user_id, permission);
CREATE INDEX IF NOT EXISTS idx_group_permissions_lookup ON group_permissions(group_id, permission);
CREATE INDEX IF NOT EXISTS idx_user_perm_lookup ON user_permissions(user_id, permission, context_key);
CREATE INDEX IF NOT EXISTS idx_group_perm_lookup ON group_permissions(group_id, permission, context_key);
CREATE INDEX IF NOT EXISTS idx_user_perm_context ON user_permissions(user_id, context_key);
CREATE INDEX IF NOT EXISTS idx_group_perm_context ON group_permissions(group_id, context_key);
CREATE INDEX IF NOT EXISTS idx_user_permissions_expiry ON user_permissions(expires_at);
CREATE INDEX IF NOT EXISTS idx_group_permissions_expiry ON group_permissions(expires_at);
CREATE INDEX IF NOT EXISTS idx_user_groups_expiry ON user_groups(expires_at);
CREATE INDEX IF NOT EXISTS idx_ladder_groups_position ON ladder_groups(ladder_id, position);
