name: PermissionsEx
main: ru.tehkode.permissions.bukkit.PermissionsEx
version: "${project.version}"
author: [t3hk0d3, zml, Rono]
api-version: 1.21
description: PermissionsEx API Adapter - A API Adapter for PermissionsEx.
depend: [PermissionsExPlus]
